### PR TITLE
Adding create or update user api

### PR DESCRIPTION
**Pull request by eSchwander**
Adding create or update user api and updated the Zendesk client's post to handle 200s.

### CODE REVIEW

**Comment by eSchwander** [comment]
Assuming this gets merged, https://github.com/nukosuke/go-zendesk/pull/169 should probably be closed.

**Comment by eSchwander** [comment]
Hi @nukosuke. Could you take a look at this if you get a chance? Thanks!

**Review by nukosuke — APPROVED** [review]
LGTM, thank you!!

**Comment by nukosuke** [comment]
@eSchwander 
Sorry for late reply. This PR has been released within [v0.10.2](https://github.com/nukosuke/go-zendesk/releases/tag/v0.10.2).
Thanks! 🙏

**Pull request merged**
