### PR TITLE
Add "Search Organizations by External ID" function

### PR DESCRIPTION
**Pull request by paoloromolini**
Add a function to search Organizations by External ID, using this API:
https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/#search-organizations-by-external-id

### CODE REVIEW

**Review by nukosuke — APPROVED** [review]

**Comment by nukosuke** [comment]
Thanks!

**Comment by dzakaammar** [comment]
hi @paoloromolini @nukosuke, I think we need to add the method to the OrganizationAPI interface, so the client that use the interface will be able to consume it. Any thoughts?

**Comment by dzakaammar** [comment]
Here I create another PR to add the method https://github.com/nukosuke/go-zendesk/pull/255 thank you!

**Comment by paoloromolini** [comment]
Thanks

**Pull request merged**
