### PR TITLE
Add Search Results Count to sdk

### PR DESCRIPTION
**Pull request by jmeridth**
- [x] add Count func to Search interface
- [x] implement Count func
- [x] add test
- [x] add profile.cov to .gitignore
- [x] update readme with info on how to regenerate mock client

Co-authored-by: Jason Meridth <jmeridth@gmail.com>
Co-authored-by: Matt Lopez <matthew.lopez4011@gmail.com>

### CODE REVIEW

**Comment by jmeridth** [comment]
Missed the mocking bit. Fixing.

**Comment by jmeridth** [comment]
@nukosuke do you have a one-liner for `mockgen` to generate all the mocks and create `zendesk/mocks/client.go` easily?  I'm brainfarting on `mockgen` right now.  Thank you in advance.  I will probably add this one-liner to the `README`

**Comment by jmeridth** [comment]
@nukosuke I added the generated `SearchCount` mocks manually to `Client.go` for now.  Can move if needed.  Thanks.

**Comment by nukosuke** [comment]
@jmeridth 

Thank you for your contribution!

> do you have a one-liner for mockgen to generate all the mocks and create zendesk/mocks/client.go easily?
You can generate mock by `go generate ./...` at project root.

**Comment by jmeridth** [comment]
@nukosuke I added that info to the README.  Thank you for that.  Cheers.

**Review by nukosuke — APPROVED** [review]
LGTM 👍 
Thank you!

**Comment by jmeridth** [comment]
@nukosuke thank you for the merge. Random question: when would a new release be done? Thank you so much for this library/sdk. Cheers.

**Comment by nukosuke** [comment]
I released [v0.9.1](https://github.com/nukosuke/go-zendesk/releases/tag/v0.9.1) which includes this PR. Thanks 👍

**Comment by jmeridth** [comment]
You are awesome. Thank you very much. Cheers.

**Pull request merged**
